name: C/C++ CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2022
  
    steps: 
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Checkout repositories
      uses: ./.github/checkout_repos

    - name: Build curl
      run: |
        mkdir external\curl\build
        cd external\curl\build
        cmake .. -G "Visual Studio 17 2022" -A Win32 -DBUILD_CURL_EXE=OFF -DBUILD_LIBCURL_DOCS=OFF -DBUILD_MISC_DOCS=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DCURL_BROTLI=OFF -DCURL_ZLIB=OFF -DCURL_ZSTD=OFF -DENABLE_CURL_MANUAL=OFF -DENABLE_THREADED_RESOLVER=OFF -DUSE_LIBIDN2=OFF -DUSE_NGHTTP2=OFF -DCURL_USE_LIBPSL=OFF -DBUILD_EXAMPLES=OFF -DCURL_USE_SCHANNEL=ON
        cmake --build . --config Release

    - name: Build server
      run: |
        mkdir build
        cd build
        cmake ..  -A Win32 -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=OFF
        cmake --build . --config Release

    - name: Build plugins
      run: |
        cd build
        cmake ..  -A Win32 -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=ON
        cmake --build . --config Release

    - name: Build client
      run: |
        cd build
        cmake ..  -A Win32 -DBUILD_CLIENT=ON -DBUILD_SERVER=OFF -DBUILD_PLUGINS=OFF
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sevenkewp-windows
        path: build/output/

  build-linux:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Checkout repositories
      uses: ./.github/checkout_repos
    
    - name: Download and install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install gcc-multilib g++-multilib libc6-dev-i386 mesa-common-dev libssl-dev:i386

    - name: Build curl
      run: |
        mkdir external/curl/build
        cd external/curl/build
        cmake .. -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32" -DBUILD_CURL_EXE=OFF -DBUILD_LIBCURL_DOCS=OFF -DBUILD_MISC_DOCS=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DCURL_BROTLI=OFF -DCURL_ZLIB=OFF -DCURL_ZSTD=OFF -DENABLE_CURL_MANUAL=OFF -DENABLE_THREADED_RESOLVER=OFF -DUSE_LIBIDN2=OFF -DUSE_NGHTTP2=OFF -DCURL_USE_LIBPSL=OFF -DBUILD_EXAMPLES=OFF
        cmake --build . --config Release

    - name: Build server
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=OFF
        cmake --build .

    - name: Build plugins
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=ON
        cmake --build .

    - name: Build client
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=ON -DBUILD_SERVER=OFF -DBUILD_PLUGINS=OFF
        cmake --build .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sevenkewp-linux
        path: build/output/
